import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {JSDOM,VirtualConsole} from 'jsdom';import {indexedDB} from 'fake-indexeddb';
const require=createRequire(import.meta.url),canvas=require('@napi-rs/canvas');globalThis.DOMMatrix=canvas.DOMMatrix;globalThis.ImageData=canvas.ImageData;globalThis.Path2D=canvas.Path2D;globalThis.indexedDB=indexedDB;
const root=new URL('../',import.meta.url).pathname.replace(/\/$/,'');const model=await import(root+'/src/model.js'),pdf=await import(root+'/src/pdf-import.js');
const fixture=new File([fs.readFileSync(new URL('./generated-fixture.pdf',import.meta.url))],'fixture.pdf',{type:'application/pdf'});
const renderer=(file,options)=>pdf.importPDF(file,{...options,canvasFactory:()=>{const c=canvas.createCanvas(2,2);c.toBlob=async cb=>cb(new Blob([await c.encode('png')],{type:'image/png'}));return c}});
const source=fs.readFileSync(root+'/src/app.js','utf8').replace(/^import .*;\n/gm,'');
function create(){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'https://example.test/repository/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;Object.assign(w,model,{importPDF:renderer,File:globalThis.File,Blob:globalThis.Blob});w.URL.createObjectURL=URL.createObjectURL;w.URL.revokeObjectURL=URL.revokeObjectURL;w.confirm=()=>true;w.prompt=()=>null;w.CSS={escape:s=>s};Object.defineProperty(w.HTMLElement.prototype,'clientWidth',{get(){return this.id==='viewport'?390:320}});Object.defineProperty(w.HTMLElement.prototype,'clientHeight',{get(){return this.id==='viewport'?620:320}});w.eval(source+"\nwindow.__qaPlace=()=>{const p=project.pages[page];selectAt(tx+.2*p.width*scale,ty+.3*p.height*scale);selectAt(tx+.4*p.width*scale,ty+.5*p.height*scale)}");return {dom,w,d:w.document,errors}}
const tick=()=>new Promise(r=>setTimeout(r,10));
let {dom,w,d,errors}=create();await tick();assert.equal(d.getElementById('add').disabled,true);w.testFile=fixture;await w.eval('choosePDF(testFile)');assert.equal(d.getElementById('add').disabled,false);assert.equal(d.querySelectorAll('#hall option').length,2);assert.equal((await model.loadProject()).pages.length,2);
d.getElementById('add').click();d.getElementById('booth').value='A12';d.getElementById('circle').value='Circle';let row=d.querySelector('.goods-input-row');row.querySelector('.item-name').value='Book';row.querySelector('.item-price').value='800';d.getElementById('url').value='https://example.test/book';d.getElementById('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.getElementById('confirm-bar').hidden,false);await w.eval('save()');assert.equal(d.getElementById('count').textContent,'1');let state=await model.loadProject();assert.equal(state.links[0].items[0].price,800);assert.equal(state.links[0].circle,'Circle');const saved=state.links[0];
dom.window.close();({dom,w,d,errors}=create());await tick();assert.equal(d.getElementById('count').textContent,'1');assert.equal(d.querySelectorAll('#hall option').length,2);
d.getElementById('hall').value='1';d.getElementById('hall').dispatchEvent(new w.Event('change'));assert.equal(d.getElementById('map-image').alt,'fixture.pdf 2 / 2');d.getElementById('add').click();d.getElementById('booth').value='Custom-9';d.getElementById('manual-start').click();assert.equal(d.getElementById('save').disabled,true);w.__qaPlace();assert.equal(d.getElementById('save').disabled,false);await w.eval('save()');assert.equal(d.getElementById('count').textContent,'2');state=await model.loadProject();assert.equal(state.links[0].page,1);assert(Math.abs(state.links[0].w-20)<.001);
const backup={format:'space-link-map-backup',version:1,document:{name:state.fileName,sha256:state.sha256},links:state.links};w.testBackup=new File([JSON.stringify(backup)],'backup.json');await w.eval('restoreBackup(testBackup)');assert.equal(d.getElementById('count').textContent,'2');const wrong={...backup,document:{...backup.document,sha256:'a'.repeat(64)}};w.badBackup=new File([JSON.stringify(wrong)],'wrong.json');await w.eval('restoreBackup(badBackup)');assert.equal((await model.loadProject()).links.length,2);assert.match(d.getElementById('toast').textContent,/同じPDF/);
const full={...backup,pdfBase64:model.bytesToBase64(new Uint8Array(await state.pdf.arrayBuffer()))};await w.eval('clearProject()');assert.equal(await model.loadProject(),null);assert.equal(d.getElementById('add').disabled,true);w.fullBackup=new File([JSON.stringify(full)],'full.json');await w.eval('restoreBackup(fullBackup)');assert.equal(d.getElementById('count').textContent,'2');assert.equal((await model.loadProject()).sha256,state.sha256);
w.badPDF=new File(['garbage'],'bad.pdf');await w.eval('choosePDF(badPDF)');assert.equal(d.getElementById('count').textContent,'2');assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: actual PDF import through UI action, IndexedDB reload, text match, form fields/prices, page change, manual two-corner region, metadata backup restore, wrong-PDF rejection, clear, full PDF backup restore, invalid-PDF preservation');dom.window.close();
