import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as canvas from '@napi-rs/canvas';
import {gridBounds} from '../src/grid.js';
Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,ImageData:canvas.ImageData,Path2D:canvas.Path2D});
const {importPDF,createDetailRenderer}=await import('../src/pdf-import.js');
const file=new File([fs.readFileSync(new URL('./generated-fixture.pdf',import.meta.url))],'fixture.pdf');
function canvasFactory(){const c=canvas.createCanvas(2,2);c.toBlob=async cb=>cb(new Blob([await c.encode('png')],{type:'image/png'}));return c}
const project=await importPDF(file,{canvasFactory}),page=project.pages[0];
const bitmap=await canvas.loadImage(Buffer.from(await page.blob.arrayBuffer()));
const overview=canvas.createCanvas(page.width,page.height),ctx=overview.getContext('2d');ctx.drawImage(bitmap,0,0);
const text=page.texts.find(t=>t.text==='A12');assert(text);
const cell=gridBounds(ctx.getImageData(0,0,page.width,page.height),text);assert(cell,'closed cell found around actual PDF label');
for(const [key,value] of Object.entries({x:25,y:44,w:25,h:12}))assert(Math.abs(cell[key]-value)<.3,`${key}: ${cell[key]}`);
const region={x:cell.x/100*page.width,y:cell.y/100*page.height,w:cell.w/100*page.width,h:cell.h/100*page.height};
const renderer=createDetailRenderer(project.pdf,{canvasFactory});
const detail=await renderer.render(0,page,region,4);
assert.equal(detail.width,Math.ceil(region.w*4));assert.equal(detail.height,Math.ceil(region.h*4));
const pixels=detail.getContext('2d').getImageData(0,0,detail.width,detail.height).data;
let ink=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]<128)ink++;
assert(ink>500,'zoomed crop contains the original label and borders');
const limited=await renderer.render(0,page,region,100);assert(limited.width<=4096&&limited.height<=4096);assert(limited.width*limited.height<4010000);
const [stale,current]=await Promise.all([renderer.render(0,page,region,2),renderer.render(1,project.pages[1],region,2)]);
assert.equal(stale,null);assert(current);renderer.destroy();
ctx.fillStyle='white';ctx.fillRect(0,0,page.width,page.height);
assert.equal(gridBounds(ctx.getImageData(0,0,page.width,page.height),text),null,'no fabricated cell for a borderless label');
ctx.strokeStyle='black';ctx.lineWidth=2;ctx.strokeRect(220,484,220,132);ctx.fillRect(219,480,5,145);
assert.equal(gridBounds(ctx.getImageData(0,0,page.width,page.height),text),null,'open rectangle rejected');
console.log('PASS: actual PDF grid bounds, high-resolution cropped rendering, canvas budget, stale render cancellation, missing/open cell rejection');
