import {loadProject,saveProject,deleteProject,normalizeId,validURL,validateLink,findTextCandidates,boundsFromCorners,parseBackup,bytesToBase64,base64ToBytes,LIMITS} from './model.js';
import {importPDF} from './pdf-import.js';
const $=s=>document.querySelector(s),colors=[['#ef4674','ピンク'],['#2d72e2','青'],['#159775','緑'],['#e7a01c','黄'],['#9957d6','紫']];
let project=null,page=0,color=colors[0][0],pending=null,manual=false,corner=null,scale=1,fitScale=1,tx=0,ty=0,moveStart=null,panMoved=false,lastGesture=null,toastTimer,busy=false,editingId=null;
const points=new Map(),imageURLs=new Map();
function message(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',5000)}
function busyState(active,title='処理しています',progress=''){busy=active;$('#busy').hidden=!active;$('#busy-title').textContent=title;$('#busy-progress').textContent=progress}
function clearURLs(){for(const url of imageURLs.values())URL.revokeObjectURL(url);imageURLs.clear()}
function imageURL(n){if(!imageURLs.has(n))imageURLs.set(n,URL.createObjectURL(project.pages[n].blob));return imageURLs.get(n)}
function transform(){if(!project)return;const p=project.pages[page];Object.assign($('#surface').style,{width:p.width+'px',height:p.height+'px',transform:`translate(${tx}px,${ty}px) scale(${scale})`});$('#zoom-level').textContent=Math.round(scale/fitScale*100)+'%'}
function fit(){if(!project)return;const v=$('#viewport'),p=project.pages[page];fitScale=Math.min((v.clientWidth-26)/p.width,(v.clientHeight-24)/p.height);scale=fitScale;tx=(v.clientWidth-p.width*scale)/2;ty=(v.clientHeight-p.height*scale)/2;transform()}
function zoom(factor,cx=$('#viewport').clientWidth/2,cy=$('#viewport').clientHeight/2){if(!project)return;const old=scale;scale=Math.min(fitScale*20,Math.max(fitScale*.8,scale*factor));tx=cx-(cx-tx)*scale/old;ty=cy-(cy-ty)*scale/old;transform()}
function showPage(n){if(!project||n<0||n>=project.pages.length)return;page=n;$('#hall').value=n;$('#map-image').src=imageURL(n);$('#map-image').alt=project.fileName+' '+project.pages[n].name;renderOverlays();fit()}
function focusRegion(r){if(page!==r.page)showPage(r.page);const v=$('#viewport'),p=project.pages[page];scale=fitScale*4;tx=v.clientWidth/2-(r.x+r.w/2)/100*p.width*scale;ty=(v.clientHeight-(pending?120:0))/2-(r.y+r.h/2)/100*p.height*scale;transform()}
function renderProject(){clearURLs();$('#hall').replaceChildren();$('#empty-map').hidden=!!project;$('#surface').hidden=!project;$('#add').disabled=!project;$('#hall').disabled=!project;$('#clear-project').disabled=!project;$('#document-name').textContent=project?.fileName||'';if(project){project.pages.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;$('#hall').append(o)});showPage(Math.min(page,project.pages.length-1))}else{$('#map-image').removeAttribute('src');$('#overlays').replaceChildren();$('#count').textContent='0'}renderLinks()}
function renderPreview(){const el=$('#preview-mark');el.hidden=!pending||pending.page!==page||pending.w<=0||pending.h<=0;if(!el.hidden)Object.assign(el.style,{left:pending.x+'%',top:pending.y+'%',width:pending.w+'%',height:pending.h+'%',borderColor:pending.color,backgroundColor:pending.color+'55'})}
function renderOverlays(){const wrap=$('#overlays');wrap.replaceChildren();for(const r of project?.links.filter(r=>r.page===page)||[]){const a=document.createElement('a');a.className='marker';Object.assign(a.style,{left:r.x+'%',top:r.y+'%',width:r.w+'%',height:r.h+'%'});a.style.setProperty('--mark',r.color);a.href=r.url||'#';a.target='_blank';a.rel='noopener noreferrer';a.title=r.booth+(r.circle?' · '+r.circle:'');a.setAttribute('aria-label',r.booth+(r.url?' のリンクを開く':' の登録情報を見る'));a.onclick=e=>{if(manual||(panMoved&&e.detail!==0)){e.preventDefault();return}const overlapping=project.links.filter(t=>t.page===r.page&&Math.abs(t.x-r.x)<.05&&Math.abs(t.y-r.y)<.05);if(!r.url||overlapping.length>1){e.preventDefault();showPanel('list');$('#saved-list').querySelector(`[data-id="${CSS.escape(r.id)}"]`)?.scrollIntoView?.({block:'nearest'});if(overlapping.length>1)message('重なる登録があります。一覧から選んでください')}};wrap.append(a)}renderPreview()}
function renderLinks(){const links=project?.links||[];$('#count').textContent=links.length;renderOverlays();const list=$('#saved-list');list.replaceChildren();if(!links.length){const p=document.createElement('p');p.className='empty';p.textContent=project?'まだ登録がありません。＋登録から追加できます。':'まず、ご自身のPDFを取り込んでください。';list.append(p);return}for(const r of links){const item=document.createElement('article');item.className='saved-item';item.dataset.id=r.id;const top=document.createElement('div');top.className='saved-top';const sw=document.createElement('span');sw.className='saved-swatch';sw.style.background=r.color;const title=document.createElement('span');title.className='saved-title';title.textContent=r.booth;top.append(sw,title);const hall=document.createElement('p');hall.className='saved-hall';hall.textContent='ページ '+(r.page+1);item.append(top,hall);if(r.circle){const p=document.createElement('p');p.className='saved-circle';p.textContent=r.circle;item.append(p)}if(r.items.length){const ul=document.createElement('ul');ul.className='saved-goods';for(const g of r.items){const li=document.createElement('li'),name=document.createElement('span'),price=document.createElement('span');name.className='goods-name';price.className='goods-price';name.textContent=g.name;price.textContent=g.price===null?'価格未入力':'¥'+g.price.toLocaleString('ja-JP');li.append(name,price);ul.append(li)}item.append(ul)}if(r.url){const a=document.createElement('a');a.className='saved-url';a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=r.url;item.append(a)}const actions=document.createElement('div');actions.className='saved-actions';for(const [label,fn,cl]of [['地図で見る',()=>{closePanel();focusRegion(r)},''],['編集',()=>{fillForm(r);showPanel('form')},''],['削除',()=>removeLink(r),'delete']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cl;b.onclick=fn;actions.append(b)}item.append(actions);list.append(item)}}
function showPanel(view){$('#panel').hidden=false;$('#form-view').hidden=view!=='form';$('#list-view').hidden=view!=='list';$('#panel-title').textContent=view==='form'?'スペースを登録':'登録済みのスペース';if(view==='form')setTimeout(()=>$('#booth').focus(),80)}
function closePanel(){$('#panel').hidden=true}
function setColor(c){color=c;for(const b of $('#colors').children)b.setAttribute('aria-checked',String(b.dataset.color===c))}
function addItem(value={name:'',price:null}){if($('#goods-inputs').children.length>=LIMITS.items){message('販売物は50件までです');return}const row=document.createElement('div');row.className='goods-input-row';const name=document.createElement('input');name.className='item-name';name.placeholder='本・販売物の名前';name.maxLength=120;name.setAttribute('aria-label','本・販売物の名前');name.value=value.name;const price=document.createElement('input');price.className='item-price';price.type='number';price.min='0';price.step='1';price.max='100000000';price.inputMode='numeric';price.placeholder='価格（円）';price.setAttribute('aria-label','価格（円）');price.value=value.price??'';const remove=document.createElement('button');remove.type='button';remove.textContent='✕';remove.setAttribute('aria-label','この品目を削除');remove.onclick=()=>row.remove();row.append(name,price,remove);$('#goods-inputs').append(row)}
function setItems(items=[]){$('#goods-inputs').replaceChildren();for(const item of items.length?items:[{name:'',price:null}])addItem(item)}
function resetForm(){$('#form').reset();setItems();setColor(colors[0][0]);editingId=null;$('#form-error').textContent=''}
function fillForm(r){stopPreview();editingId=r.id;$('#booth').value=r.booth;$('#circle').value=r.circle;$('#url').value=r.url;setItems(r.items);setColor(r.color);$('#form-error').textContent=''}
function readForm(){const booth=$('#booth').value.trim(),circle=$('#circle').value.trim(),url=validURL($('#url').value.trim()),items=[];if(url===null)throw Error('http:// または https:// から始まるURLを入力してください');for(const row of $('#goods-inputs').children){const name=row.querySelector('.item-name').value.trim(),raw=row.querySelector('.item-price').value;if(!name&&!raw)continue;items.push({name,price:raw===''?null:Number(raw)})}return validateLink({booth,circle,url,color,items,page,x:0,y:0,w:1,h:1},project.pages.length)}
function stage(manualOnly=false){if(!project||busy)return;$('#form-error').textContent='';try{const values=readForm(),existing=project.links.find(r=>r.id===editingId);let region;if(!manualOnly&&existing&&normalizeId(existing.booth)===normalizeId(values.booth))region=existing;else if(!manualOnly){const hits=findTextCandidates(project.pages,values.booth);if(hits.length!==1){$('#form-error').textContent=hits.length?'同じ文字が複数あります。地図で範囲を指定してください。':'完全一致する文字がありません。画像PDFや分かれた表記は、地図で範囲を指定してください。';return}region=hits[0]}pending={...values,...(region||{page,x:0,y:0,w:0,h:0}),...values,...(region?{page:region.page,x:region.x,y:region.y,w:region.w,h:region.h}: {w:0,h:0})};manual=manualOnly;corner=null;closePanel();$('#confirm-bar').hidden=false;document.body.classList.add('confirming');$('#preview-label').textContent=pending.booth;$('#preview-help').textContent=manual?'囲みたい範囲の1つ目の角をタップしてください。':'PDF内の文字位置が候補です。スペースの枠と一致するか確認し、必要なら範囲を指定してください。';$('#save-error').textContent='';$('#save').disabled=manual;$('#viewport').classList.toggle('selecting',manual);renderPreview();if(region)focusRegion(pending)}catch(e){$('#form-error').textContent=e.message}}
function stopPreview(){pending=null;manual=false;corner=null;$('#confirm-bar').hidden=true;document.body.classList.remove('confirming');$('#viewport').classList.remove('selecting');$('#preview-mark').hidden=true;$('#save-error').textContent=''}
function selectAt(cx,cy){if(!project||!pending||!manual)return;const p=project.pages[page],point={x:(cx-tx)/scale/p.width*100,y:(cy-ty)/scale/p.height*100};if(point.x<0||point.y<0||point.x>100||point.y>100)return;if(!corner){corner=point;Object.assign(pending,{page,x:point.x,y:point.y,w:Math.min(.2,100-point.x),h:Math.min(.2,100-point.y)});$('#save').disabled=true;$('#preview-help').textContent='反対側の角をタップしてください。ドラッグやピンチで移動・拡大できます。'}else{const rect=boundsFromCorners(corner,point);if(rect.w<.15||rect.h<.15){message('少し離れた反対側の角を選んでください');return}Object.assign(pending,{page,...rect});corner=null;manual=false;$('#viewport').classList.remove('selecting');$('#save').disabled=false;$('#preview-help').textContent='囲んだ範囲とスペース番号が一致するか確認してください。'}renderPreview()}
async function save(){if(busy||!project||!pending)return;try{const record=validateLink(pending,project.pages.length),existing=project.links.find(r=>normalizeId(r.booth)===normalizeId(record.booth));record.id=editingId||existing?.id||record.id;record.updatedAt=new Date().toISOString();const next={...project,links:[record,...project.links.filter(r=>r.id!==record.id&&normalizeId(r.booth)!==normalizeId(record.booth))]};busyState(true,'登録を保存しています');await saveProject(next);project=next;stopPreview();renderLinks();resetForm();message('この端末に保存しました')}catch(e){$('#save-error').textContent='保存できませんでした。入力は残っています。'+(e.message||'')}finally{busyState(false)}}
async function removeLink(r){if(busy||!confirm(r.booth+' の登録を削除しますか？'))return;try{busyState(true,'登録を削除しています');const next={...project,links:project.links.filter(x=>x.id!==r.id)};await saveProject(next);project=next;renderLinks()}catch{message('削除できませんでした。再試行してください')}finally{busyState(false)}}
async function readPDF(file){return importPDF(file,{progress:(n,total)=>$('#busy-progress').textContent=`${n} / ${total} ページを準備中`,password:wrong=>prompt(wrong?'パスワードが違います。もう一度入力してください':'このPDFのパスワードを入力してください')})}
async function choosePDF(file){if(!file||busy)return;if(project&&!confirm('PDFを変更すると、現在のPDFと登録は置き換わります。必要なら先にバックアップしてください。変更しますか？'))return;try{busyState(true,'PDFをこの端末で読み込んでいます');const next=await readPDF(file);await saveProject(next);project=next;page=0;stopPreview();resetForm();renderProject();message('PDFをこの端末に保存しました')}catch(e){message('読み込めませんでした。現在のデータは変更していません。'+(e.message||''))}finally{busyState(false)}}
async function exportBackup(){if(busy||!project){message('先にPDFを取り込んでください');return}try{const value={format:'space-link-map-backup',version:1,document:{name:project.fileName,sha256:project.sha256},links:project.links};if($('#include-pdf').checked)value.pdfBase64=bytesToBase64(new Uint8Array(await project.pdf.arrayBuffer()));const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='space-map-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{message('バックアップを作成できませんでした')}}
async function restoreBackup(file){if(!file||busy)return;try{if(file.size>LIMITS.backupBytes)throw Error('バックアップは45 MB以下で選んでください');const value=parseBackup(JSON.parse(await file.text()));if(project&&!confirm('バックアップの内容で現在の登録を置き換えます。復元しますか？'))return;busyState(true,'バックアップを復元しています');let next;if(value.pdfBase64){const bytes=base64ToBytes(value.pdfBase64);next=await readPDF(new File([bytes],value.document.name||'map.pdf',{type:'application/pdf'}));if(next.sha256!==value.document.sha256)throw Error('PDFとバックアップの情報が一致しません')}else{if(!project||project.sha256!==value.document.sha256)throw Error('先に、このバックアップと同じPDFを取り込んでください');next={...project}}next.links=value.links.map(r=>validateLink(r,next.pages.length));const keys=next.links.map(r=>normalizeId(r.booth));if(new Set(keys).size!==keys.length||new Set(next.links.map(r=>r.id)).size!==next.links.length)throw Error('登録が重複しています');await saveProject(next);project=next;page=0;stopPreview();resetForm();renderProject();message('バックアップを復元しました')}catch(e){message('復元できませんでした。現在のデータは変更していません。'+(e.message||''))}finally{busyState(false)}}
async function clearProject(){if(busy||!project||!confirm('この端末に保存したPDFとすべての登録を消去します。元には戻せません。消去しますか？'))return;try{busyState(true,'端末内のデータを消去しています');await deleteProject();project=null;page=0;stopPreview();resetForm();closePanel();renderProject();message('PDFと登録を消去しました')}catch{message('消去できませんでした')}finally{busyState(false)}}
for(const [c,name]of colors){const b=document.createElement('button');b.type='button';b.className='color-option';b.style.setProperty('--color',c);b.dataset.color=c;b.setAttribute('role','radio');b.setAttribute('aria-label',name);b.onclick=()=>setColor(c);$('#colors').append(b)}$('#colors').setAttribute('role','radiogroup');$('#colors').setAttribute('aria-label','色');setColor(color);setItems();
$('#add-item').onclick=()=>addItem();$('#add').onclick=()=>{if(project){stopPreview();resetForm();showPanel('form')}};$('#close').onclick=closePanel;$('#list-open').onclick=()=>showPanel('list');$('#hall').onchange=()=>{showPage(Number($('#hall').value));if(manual){corner=null;pending.page=page;pending.w=0;pending.h=0;$('#save').disabled=true;$('#preview-help').textContent='囲みたい範囲の1つ目の角をタップしてください。';renderPreview()}};$('#form').onsubmit=e=>{e.preventDefault();stage()};$('#manual-start').onclick=()=>stage(true);$('#back-edit').onclick=()=>{stopPreview();showPanel('form')};$('#adjust').onclick=()=>{manual=true;corner=null;$('#viewport').classList.add('selecting');$('#preview-help').textContent='囲みたい範囲の1つ目の角をタップしてください。';$('#save').disabled=true};$('#save').onclick=save;$('#zoom-in').onclick=()=>zoom(1.5);$('#zoom-out').onclick=()=>zoom(1/1.5);$('#fit').onclick=fit;
for(const id of ['import-open','empty-import'])$('#'+id).onclick=()=>{if(!busy)$('#pdf-file').click()};$('#pdf-file').onchange=async e=>{await choosePDF(e.target.files[0]);e.target.value=''};$('#backup').onclick=exportBackup;$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async e=>{await restoreBackup(e.target.files[0]);e.target.value=''};$('#clear-project').onclick=clearProject;
const v=$('#viewport');function local(e){const r=v.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top}}function gesture(){const p=[...points.values()];return p.length===2?{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}:null}
v.addEventListener('pointerdown',e=>{if(!project||e.button>0||busy)return;const p=local(e);points.set(e.pointerId,p);v.setPointerCapture(e.pointerId);moveStart={...p,tx,ty};panMoved=false;lastGesture=gesture()});v.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;const p=local(e);points.set(e.pointerId,p);if(points.size>=2){const g=gesture();if(g&&lastGesture){zoom(g.d/lastGesture.d,lastGesture.x,lastGesture.y);tx+=g.x-lastGesture.x;ty+=g.y-lastGesture.y;transform();panMoved=true}lastGesture=g}else if(moveStart){const dx=p.x-moveStart.x,dy=p.y-moveStart.y;if(Math.hypot(dx,dy)>5)panMoved=true;tx=moveStart.tx+dx;ty=moveStart.ty+dy;transform()}});v.addEventListener('pointerup',e=>{if(!points.has(e.pointerId))return;const p=local(e),single=points.size===1;points.delete(e.pointerId);if(single&&!panMoved){if(manual)selectAt(p.x,p.y);else{const el=document.elementFromPoint(e.clientX,e.clientY);if(el?.classList.contains('marker'))el.click()}}if(points.size===1)moveStart={...[...points.values()][0],tx,ty};else moveStart=null;lastGesture=gesture()});v.addEventListener('pointercancel',e=>{points.delete(e.pointerId);moveStart=null;lastGesture=null;panMoved=true});v.addEventListener('wheel',e=>{if(!project)return;e.preventDefault();const p=local(e);zoom(Math.exp(-e.deltaY*.002),p.x,p.y)},{passive:false});v.addEventListener('keydown',e=>{if(!project)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','+','-'].includes(e.key)){e.preventDefault();if(e.key==='+')zoom(1.5);else if(e.key==='-')zoom(1/1.5);else{tx+=e.key==='ArrowLeft'?50:e.key==='ArrowRight'?-50:0;ty+=e.key==='ArrowUp'?50:e.key==='ArrowDown'?-50:0;transform()}}});window.addEventListener('resize',()=>{if(pending&&pending.w)focusRegion(pending);else fit()});window.addEventListener('pagehide',clearURLs);
async function init(){try{project=await loadProject();if(project&&(!Array.isArray(project.pages)||!project.pages.length||!project.pdf))throw Error('保存形式を確認できません');renderProject()}catch{message('端末内のデータを読み込めません。ブラウザの保存設定を確認してください。')}}
async function offline(){if(!('serviceWorker'in navigator)||!/^https?:$/.test(location.protocol)){$('#offline-status').textContent='HTTPSまたはlocalhostで開いてください';return}try{const reg=await navigator.serviceWorker.register('./sw.js');if(reg.installing)await new Promise((resolve,reject)=>{const worker=reg.installing;worker.addEventListener('statechange',()=>{if(worker.state==='activated')resolve();if(worker.state==='redundant')reject(Error('install failed'))})});const ready=await navigator.serviceWorker.ready;const result=await new Promise((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(Error('timeout')),12000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data)};ready.active.postMessage({type:'CHECK_CACHE'},[channel.port2])});if(!result.ready)throw Error('cache incomplete');$('#offline-status').textContent='オフライン準備完了'}catch{$('#offline-status').textContent='オフライン準備未完了：オンラインで再読み込み'}}
init();offline();
